name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: deployment
    runs-on: ubuntu-latest
    
    steps:
    - name: deploy
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.SSH_HOST  }}
          USER_NAME : ${{ secrets.SSH_USER  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} -p 22 '
          cd ${{ secrets.WORK_DIR }} &&
          git reset --hard &&
          git checkout ${{ secrets.MAIN_BRANCH }} &&
          git pull origin ${{ secrets.MAIN_BRANCH }} &&
          npm ci &&
          npx prisma generate &&
          npm run swagger ${{ secrets.HOST_IP }} 443 &&
          pm2 restart all &&
          exit
        '
    - name: cleanup
      run: rm -rf ~/.ssh